//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ballazza.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Booking
    {
      
        public int BookingId { get; set; }
        public string Id { get; set; }
        public int WorkshopId { get; set; }
        [Required(ErrorMessage = "Booking date cannot be empty")]
        [DataType(DataType.DateTime)]
        public System.DateTime BookingDate { get; set; }
        
        public virtual Workshop Workshop { get; set; }
    }
}
