//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ballazza.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Booking
    {
        [Required]
        public int BookingId { get; set; }
        [Required]
        public string Id { get; set; }
        [Required]
        public int WorkshopId { get; set; }
        [Required]
        public System.DateTime BookingDate { get; set; }
        public virtual Workshop Workshop { get; set; }
    }
}
