//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ballazza.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Venue
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Venue()
        {
            this.Ratings = new HashSet<Rating>();
            this.Workshops = new HashSet<Workshop>();
        }

        [Display(Name = "Id")]
        public int VenueId { get; set; }
        [Display(Name = "Name")]
        public string VenueName { get; set; }
        [Display(Name = "Street")]
        public string VenueStreet { get; set; }
        [Display(Name = "Suburb")]
        public string VenueSuburb { get; set; }
        [Display(Name = "State")]
        public string VenueState { get; set; }
        [Display(Name = "Post code")]
        public int VenuePostcode { get; set; }
        [Display(Name = "Phone number")]
        public string VenuePhoneno { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Rating> Ratings { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Workshop> Workshops { get; set; }
    }
}
